#!/usr/bin/env bash
# This script displays a list of currently running processes in a user-oriented format,
# including all processes for all users and their hierarchy.

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest
