#!/bin/bash

# This Bash script implements the FizzBuzz game.
# It displays numbers from 1 to 100, replacing multiples of 3 with "Fizz",
# multiples of 5 with "Buzz", multiples of both 3 and 5 with "FizzBuzz",
# and otherwise displaying the number itself.

for ((i=1; i<=100; i++)); do
    if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    else
        echo $i
    fi
done
