#!/usr/bin/env bash
#while loop to print Best School 10 times and say hi on num 9

num=0
while [ $num -lt 10 ];
do
    if [ $num -eq 9 ];
    then
        echo "Hi"
    fi
    echo "Best School"
    (( num++ ))
done
