#!/usr/bin/env bash
#while loop to print Best School 4_bad_luck_8_is_your_chance

num=0

while [ $num -lt 10 ]
do
  if [ $num -eq 3 ]
  then
    echo "bad luck"
  elif [ $num -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((num++ ))
done
