#!/usr/bin/env bash
# Displays the time for 12 Horus and 59 minutes.
#   Displays Hours from 0 to 12
#   Displays minutes from 1 to 59

Hour=0

while [ $Hour -le 12 ]
do
  echo "Hour: $Hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( Hour++ ))
done
