#!/usr/bin/env bash

# Loop through each file in the current directory
for file in *; do
    
    if [[ ! "$file" == .* ]]; then
        
        filename=$(echo "$file" | cut -d '-' -f2-)
       
        echo "$filename"
    fi
done
