#!/usr/bin/env bash
# This script configures the Nginx web server to run as the nginx user,
# changes its listening port to 8080, adjusts file permissions, stops Apache,
# and restarts Nginx to apply the new configuration.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
